name: "Std 002 - gitattributes"

on:
  workflow_dispatch:
    inputs:
      repository:
        description: 'Repository'
        required: true

env:
  std: "std/002-gitattributes"
  branchName: "std/002-gitattributes"
  commitMessage: "Std [002]: gitattributes"

jobs:
  main:
    name: Main
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v2
        with:
          repository: ${{ github.event.inputs.repository }}

      - name: Prepare variables
        run: echo "::set-output name=BRANCH_NAME::$(echo ${GITHUB_REF#refs/heads/})"
        id: variables

      - name: Make changes
        run: |
          curl https://raw.githubusercontent.com/${{ github.repository }}/${{ steps.variables.outputs.BRANCH_NAME }}/${{ env.std }}/gitattributes --output .gitattributes

      - name: Create PR
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.CONTRIBUTTE_PAT }}
          title: ${{ github.workflow }}
          branch: ${{ env.branchName }}
          delete-branch: true
          commit-message: ${{ env.commitMessage }}
          body: |
            Contributte standard. ğŸ‘¨ğŸ»â€ğŸ’»
            See more at [contributte/contributte](https://github.com/contributte/contributte).
